// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gztwubnglussalnktvck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dHd1Ym5nbHVzc2Fsbmt0dmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MjExNDksImV4cCI6MjA3OTQ5NzE0OX0.ga9T8vtdP3O9dQu2i-GtdENCX8_DXdwJVsjmYLQkziE";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);